feat: redux boilerplate
MangaSeed/serverless-demo-client-redux-materialui pull request #7
Opened 2019-11-13 13:15 UTC by viinxent

- created redux boilerplate
- redux / redux toolkit - configuration, typings
- redux saga - configuration, typings

2019-11-13 15:00 UTC, xuatz requested changes

2019-11-13 15:00 UTC, xuatz commented on package.json
> +    "@reduxjs/toolkit": "^1.0.4",
```suggestion
    "@reduxjs/toolkit": "1.0.4",
```
much prefer version pinning. at best I am only comfortable with ~ instead of ^

2019-11-13 15:00 UTC, xuatz commented on package.json
> +    "react-redux": "^7.1.3",
```suggestion
    "react-redux": "7.1.3",
```
smaller libraries or dev libraries might be okay but big impactful ones, better to play safe and be more predictable.

2019-11-14 07:20 UTC, viinxent commented on package.json
> +    "react-redux": "^7.1.3",
Done :smile:

2019-11-15 09:09 UTC, xuatz approved these changes

2019-11-16 03:32 UTC, merged